version: '3'

services:
  app:
    image: 598339596224.dkr.ecr.ap-south-1.amazonaws.com/hello-repository1 
    container_name: BACKEND
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - database
    networks:
      - network

  database:
    image: postgres:latest
    container_name: DATABASE
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - network

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  network:
    driver: bridge
